name: pull request
on:
  pull_request:
    branches:
      - master
jobs:
  testAndBuild:
    name: Test and Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
      - name: Install Dependencies
        run: npm ci
      - name: Test
        run: npm test
      - name: Build
        run: npm run build
